### PR TITLE
fix: translations load for anime route

### LINKED ISSUE #315: Translations not loading on specific url pattern
eg: not working pattern: `http://localhost:5174/anime/1/episode/1`
working pattern: `http://localhost:5174/anime/mal/1/episode/1`

`mal` can be anything from `anime` url params matcher

### PR DESCRIPTION
**Pull request by moonlitgrace**
Fix #315

### CODE REVIEW

**Comment by baseplate-admin** [comment]
And this is exactly what i didn't want

File: src/lib/translations/index.ts [hunk 1]
```diff
@@ -3,57 +3,57 @@ import { dev } from "$app/environment";
 import lang from "./lang.json" assert { type: "json" };
 
 const route_table = {
-	anime: /^\/anime(?:\/[^\/]+\/\d+)*(?:\/episodes\/\d+)?$/
+  anime: /^\/anime\/?.*$/
```
Comment (baseplate-admin) [inline src/lib/translations/index.ts:6]: Please revert this. We want strong typed routes
